---
- name: celery | install CeleryBeat upstart jobs
  sudo: yes
  template: >
    src=upstart.celerybeat.conf.j2
    dest=/etc/init/celerybeat.conf
  notify:
    - restart celery beat
  tags:
    - celery

- name: celery | install Celery Worker upstart jobs
  sudo: yes
  template: >
    src=upstart.celeryworker.conf.j2
    dest=/etc/init/celeryworker.conf
  notify:
    - restart celery workers
  tags:
    - celery
